/**
 * EJS template strings for the ContextKit documentation site.
 *
 * All templates use Tailwind CDN for styling and are rendered
 * via `ejs.render()` with embedded template strings.
 */

// ---------------------------------------------------------------------------
// Shared layout helpers
// ---------------------------------------------------------------------------

const HEAD = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= pageTitle %> — <%= siteTitle %></title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>`;

const NAV = `<nav class="bg-gray-900 text-white px-6 py-3 flex items-center gap-6">
  <a href="<%= basePath %>/" class="font-bold text-lg"><%- siteTitle %></a>
  <a href="<%= basePath %>/" class="hover:underline">Models</a>
  <a href="<%= basePath %>/glossary.html" class="hover:underline">Glossary</a>
  <a href="<%= basePath %>/search.html" class="hover:underline">Search</a>
</nav>`;

const FOOTER = `<footer class="mt-12 border-t py-4 px-6 text-gray-500 text-sm">
  Generated by <a href="https://github.com/erickittelson/ContextKit" class="underline">ContextKit</a>
</footer>`;

// ---------------------------------------------------------------------------
// Tier badge helper (used in multiple templates)
// ---------------------------------------------------------------------------

const TIER_BADGE = `<% function tierBadge(tier) {
  var colors = { none: 'bg-gray-200 text-gray-700', bronze: 'bg-amber-700 text-white', silver: 'bg-gray-400 text-white', gold: 'bg-yellow-400 text-black' };
  var cls = colors[tier] || colors.none;
  return '<span class="px-2 py-0.5 rounded text-xs font-semibold uppercase ' + cls + '">' + tier + '</span>';
} %>`;

// ---------------------------------------------------------------------------
// Index (home) template
// ---------------------------------------------------------------------------

export const indexTemplate = `${HEAD}
<body class="bg-white text-gray-900 min-h-screen">
${NAV}
${TIER_BADGE}
<main class="max-w-5xl mx-auto p-6">
  <h1 class="text-3xl font-bold mb-6"><%- siteTitle %></h1>

  <section>
    <h2 class="text-xl font-semibold mb-4">Models</h2>
    <% if (Object.keys(models).length === 0) { %>
      <p class="text-gray-500">No models found.</p>
    <% } else { %>
      <div class="grid gap-4">
        <% for (var name of Object.keys(models)) { %>
          <div class="border rounded-lg p-4 hover:shadow transition">
            <div class="flex items-center gap-3">
              <a href="<%= basePath %>/models/<%= name %>.html" class="text-lg font-medium text-blue-600 hover:underline"><%= name %></a>
              <% if (tiers[name]) { %><%- tierBadge(tiers[name].tier) %><% } %>
            </div>
            <% if (models[name].description) { %>
              <p class="text-gray-600 mt-1"><%= models[name].description %></p>
            <% } %>
            <% if (governance[name]) { %>
              <div class="flex gap-2 mt-2 text-xs text-gray-500">
                <% if (governance[name].owner) { %>
                  <span>Owner: <a href="<%= basePath %>/owners/<%= governance[name].owner %>.html" class="underline"><%= governance[name].owner %></a></span>
                <% } %>
                <% if (governance[name].trust) { %>
                  <span>Trust: <%= governance[name].trust %></span>
                <% } %>
              </div>
            <% } %>
          </div>
        <% } %>
      </div>
    <% } %>
  </section>

  <% if (Object.keys(owners).length > 0) { %>
  <section class="mt-8">
    <h2 class="text-xl font-semibold mb-4">Owners</h2>
    <ul class="space-y-1">
      <% for (var oid of Object.keys(owners)) { %>
        <li><a href="<%= basePath %>/owners/<%= oid %>.html" class="text-blue-600 hover:underline"><%= owners[oid].display_name %></a></li>
      <% } %>
    </ul>
  </section>
  <% } %>
</main>
${FOOTER}
</body>
</html>`;

// ---------------------------------------------------------------------------
// Model page template
// ---------------------------------------------------------------------------

export const modelTemplate = `${HEAD}
<body class="bg-white text-gray-900 min-h-screen">
${NAV}
${TIER_BADGE}
<main class="max-w-5xl mx-auto p-6">
  <div class="flex items-center gap-3 mb-2">
    <h1 class="text-3xl font-bold"><%= model.name %></h1>
    <% if (tier) { %><%- tierBadge(tier.tier) %><% } %>
  </div>
  <% if (model.description) { %>
    <p class="text-gray-600 mb-4"><%= model.description %></p>
  <% } %>

  <div class="flex gap-3 mb-6 text-sm">
    <a href="<%= basePath %>/models/<%= model.name %>/schema.html" class="text-blue-600 hover:underline">Schema Browser</a>
    <a href="<%= basePath %>/models/<%= model.name %>/rules.html" class="text-blue-600 hover:underline">Rules &amp; Queries</a>
  </div>

  <% if (gov) { %>
  <section class="mb-6">
    <h2 class="text-xl font-semibold mb-2">Governance</h2>
    <table class="table-auto border-collapse text-sm">
      <tbody>
        <tr><td class="pr-4 font-medium">Owner</td><td><a href="<%= basePath %>/owners/<%= gov.owner %>.html" class="text-blue-600 underline"><%= gov.owner %></a></td></tr>
        <% if (gov.trust) { %><tr><td class="pr-4 font-medium">Trust</td><td><%= gov.trust %></td></tr><% } %>
        <% if (gov.security) { %><tr><td class="pr-4 font-medium">Security</td><td><%= gov.security %></td></tr><% } %>
        <% if (gov.tags && gov.tags.length > 0) { %><tr><td class="pr-4 font-medium">Tags</td><td><%= gov.tags.join(', ') %></td></tr><% } %>
      </tbody>
    </table>
  </section>
  <% } %>

  <% if (model.datasets && model.datasets.length > 0) { %>
  <section class="mb-6">
    <h2 class="text-xl font-semibold mb-2">Datasets</h2>
    <div class="space-y-3">
      <% for (var ds of model.datasets) { %>
        <div class="border rounded p-3">
          <div class="font-medium"><%= ds.name %></div>
          <div class="text-xs text-gray-500">Source: <%= ds.source %></div>
          <% if (ds.description) { %><p class="text-sm text-gray-600 mt-1"><%= ds.description %></p><% } %>
          <% if (ds.fields && ds.fields.length > 0) { %>
            <div class="text-xs text-gray-500 mt-1"><%= ds.fields.length %> field(s)</div>
          <% } %>
        </div>
      <% } %>
    </div>
  </section>
  <% } %>

  <% if (model.relationships && model.relationships.length > 0) { %>
  <section class="mb-6">
    <h2 class="text-xl font-semibold mb-2">Relationships</h2>
    <table class="table-auto w-full text-sm border-collapse">
      <thead>
        <tr class="border-b"><th class="text-left py-1 pr-3">Name</th><th class="text-left py-1 pr-3">From</th><th class="text-left py-1">To</th></tr>
      </thead>
      <tbody>
        <% for (var rel of model.relationships) { %>
          <tr class="border-b"><td class="py-1 pr-3"><%= rel.name %></td><td class="py-1 pr-3"><%= rel.from %></td><td class="py-1"><%= rel.to %></td></tr>
        <% } %>
      </tbody>
    </table>
  </section>
  <% } %>

  <% if (model.metrics && model.metrics.length > 0) { %>
  <section class="mb-6">
    <h2 class="text-xl font-semibold mb-2">Metrics</h2>
    <div class="space-y-2">
      <% for (var metric of model.metrics) { %>
        <div class="border rounded p-3">
          <div class="font-medium"><%= metric.name %></div>
          <% if (metric.description) { %><p class="text-sm text-gray-600"><%= metric.description %></p><% } %>
        </div>
      <% } %>
    </div>
  </section>
  <% } %>

  <% if (tier) { %>
  <section class="mb-6">
    <h2 class="text-xl font-semibold mb-2">Tier Details</h2>
    <% var tierLevels = ['bronze', 'silver', 'gold']; %>
    <% for (var lvl of tierLevels) { %>
      <div class="mb-3">
        <h3 class="font-medium capitalize flex items-center gap-2">
          <%= lvl %>
          <% if (tier[lvl].passed) { %>
            <span class="text-green-600 text-xs">Passed</span>
          <% } else { %>
            <span class="text-red-500 text-xs">Not passed</span>
          <% } %>
        </h3>
        <% if (tier[lvl].checks && tier[lvl].checks.length > 0) { %>
          <ul class="text-sm ml-4 list-disc">
            <% for (var chk of tier[lvl].checks) { %>
              <li class="<%= chk.passed ? 'text-green-700' : 'text-red-600' %>"><%= chk.label %><% if (chk.detail) { %> — <%= chk.detail %><% } %></li>
            <% } %>
          </ul>
        <% } %>
      </div>
    <% } %>
  </section>
  <% } %>
</main>
${FOOTER}
</body>
</html>`;

// ---------------------------------------------------------------------------
// Schema browser template
// ---------------------------------------------------------------------------

export const schemaTemplate = `${HEAD}
<body class="bg-white text-gray-900 min-h-screen">
${NAV}
${TIER_BADGE}
<main class="max-w-5xl mx-auto p-6">
  <div class="flex items-center gap-3 mb-2">
    <h1 class="text-3xl font-bold"><%= model.name %> — Schema Browser</h1>
    <% if (tier) { %><%- tierBadge(tier.tier) %><% } %>
  </div>
  <div class="mb-4 text-sm">
    <a href="<%= basePath %>/models/<%= model.name %>.html" class="text-blue-600 hover:underline">&larr; Back to model</a>
  </div>

  <% if (model.datasets && model.datasets.length > 0) { %>
    <% for (var ds of model.datasets) { %>
      <section class="mb-8 border rounded-lg p-4">
        <h2 class="text-xl font-semibold mb-1"><%= ds.name %></h2>
        <div class="text-xs text-gray-500 mb-2">Source: <%= ds.source %></div>
        <% if (ds.description) { %><p class="text-sm text-gray-600 mb-3"><%= ds.description %></p><% } %>

        <% var dsGov = gov && gov.datasets && gov.datasets[ds.name]; %>
        <% if (dsGov) { %>
          <div class="text-xs text-gray-500 mb-3 flex gap-4">
            <% if (dsGov.grain) { %><span>Grain: <strong><%= dsGov.grain %></strong></span><% } %>
            <% if (dsGov.table_type) { %><span>Type: <strong><%= dsGov.table_type %></strong></span><% } %>
            <% if (dsGov.refresh) { %><span>Refresh: <strong><%= dsGov.refresh %></strong></span><% } %>
            <% if (dsGov.security) { %><span>Security: <strong><%= dsGov.security %></strong></span><% } %>
          </div>
        <% } %>

        <% if (ds.fields && ds.fields.length > 0) { %>
          <table class="table-auto w-full text-sm border-collapse">
            <thead>
              <tr class="border-b bg-gray-50">
                <th class="text-left py-2 px-2">Field</th>
                <th class="text-left py-2 px-2">Description</th>
                <th class="text-left py-2 px-2">Semantic Role</th>
                <th class="text-left py-2 px-2">Aggregation</th>
              </tr>
            </thead>
            <tbody>
              <% for (var field of ds.fields) { %>
                <% var fieldKey = ds.name + '.' + field.name; %>
                <% var fGov = gov && gov.fields && gov.fields[fieldKey]; %>
                <tr class="border-b">
                  <td class="py-1 px-2 font-mono text-xs"><%= field.name %></td>
                  <td class="py-1 px-2"><%= field.description || '' %></td>
                  <td class="py-1 px-2"><%= fGov && fGov.semantic_role ? fGov.semantic_role : '' %></td>
                  <td class="py-1 px-2"><%= fGov && fGov.default_aggregation ? fGov.default_aggregation : '' %></td>
                </tr>
              <% } %>
            </tbody>
          </table>
        <% } else { %>
          <p class="text-gray-400 text-sm">No fields defined.</p>
        <% } %>
      </section>
    <% } %>
  <% } else { %>
    <p class="text-gray-500">No datasets found.</p>
  <% } %>
</main>
${FOOTER}
</body>
</html>`;

// ---------------------------------------------------------------------------
// Rules page template (golden queries, business rules, guardrails)
// ---------------------------------------------------------------------------

export const rulesTemplate = `${HEAD}
<body class="bg-white text-gray-900 min-h-screen">
${NAV}
<main class="max-w-5xl mx-auto p-6">
  <h1 class="text-3xl font-bold mb-2"><%= modelName %> — Rules &amp; Queries</h1>
  <div class="mb-4 text-sm">
    <a href="<%= basePath %>/models/<%= modelName %>.html" class="text-blue-600 hover:underline">&larr; Back to model</a>
  </div>

  <% if (rules && rules.golden_queries && rules.golden_queries.length > 0) { %>
  <section class="mb-8">
    <h2 class="text-xl font-semibold mb-3">Golden Queries</h2>
    <div class="space-y-4">
      <% for (var gq of rules.golden_queries) { %>
        <div class="border rounded-lg p-4">
          <div class="font-medium mb-2"><%= gq.question %></div>
          <pre class="bg-gray-100 rounded p-3 text-sm overflow-x-auto"><code><%= gq.sql %></code></pre>
          <% if (gq.dialect) { %><div class="text-xs text-gray-500 mt-1">Dialect: <%= gq.dialect %></div><% } %>
          <% if (gq.tags && gq.tags.length > 0) { %><div class="text-xs text-gray-500 mt-1">Tags: <%= gq.tags.join(', ') %></div><% } %>
        </div>
      <% } %>
    </div>
  </section>
  <% } %>

  <% if (rules && rules.business_rules && rules.business_rules.length > 0) { %>
  <section class="mb-8">
    <h2 class="text-xl font-semibold mb-3">Business Rules</h2>
    <div class="space-y-3">
      <% for (var br of rules.business_rules) { %>
        <div class="border rounded p-4">
          <div class="font-medium"><%= br.name %></div>
          <p class="text-sm text-gray-600 mt-1"><%= br.definition %></p>
          <% if (br.enforcement && br.enforcement.length > 0) { %>
            <div class="text-xs text-gray-500 mt-1">Enforcement: <%= br.enforcement.join(', ') %></div>
          <% } %>
          <% if (br.avoid && br.avoid.length > 0) { %>
            <div class="text-xs text-red-500 mt-1">Avoid: <%= br.avoid.join(', ') %></div>
          <% } %>
        </div>
      <% } %>
    </div>
  </section>
  <% } %>

  <% if (rules && rules.guardrail_filters && rules.guardrail_filters.length > 0) { %>
  <section class="mb-8">
    <h2 class="text-xl font-semibold mb-3">Guardrail Filters</h2>
    <div class="space-y-3">
      <% for (var gf of rules.guardrail_filters) { %>
        <div class="border rounded p-4">
          <div class="font-medium"><%= gf.name %></div>
          <pre class="bg-gray-100 rounded p-2 text-sm mt-1"><code><%= gf.filter %></code></pre>
          <p class="text-sm text-gray-600 mt-1"><%= gf.reason %></p>
        </div>
      <% } %>
    </div>
  </section>
  <% } %>

  <% if (rules && rules.hierarchies && rules.hierarchies.length > 0) { %>
  <section class="mb-8">
    <h2 class="text-xl font-semibold mb-3">Hierarchies</h2>
    <div class="space-y-3">
      <% for (var h of rules.hierarchies) { %>
        <div class="border rounded p-4">
          <div class="font-medium"><%= h.name %></div>
          <div class="text-sm text-gray-600 mt-1">Dataset: <%= h.dataset %></div>
          <div class="text-sm text-gray-600">Levels: <%= h.levels.join(' &rarr; ') %></div>
        </div>
      <% } %>
    </div>
  </section>
  <% } %>

  <% if (!rules || ((!rules.golden_queries || rules.golden_queries.length === 0) && (!rules.business_rules || rules.business_rules.length === 0) && (!rules.guardrail_filters || rules.guardrail_filters.length === 0) && (!rules.hierarchies || rules.hierarchies.length === 0))) { %>
    <p class="text-gray-500">No rules or queries defined for this model.</p>
  <% } %>
</main>
${FOOTER}
</body>
</html>`;

// ---------------------------------------------------------------------------
// Glossary template
// ---------------------------------------------------------------------------

export const glossaryTemplate = `${HEAD}
<body class="bg-white text-gray-900 min-h-screen">
${NAV}
<main class="max-w-5xl mx-auto p-6">
  <h1 class="text-3xl font-bold mb-6">Glossary</h1>

  <% var termIds = Object.keys(terms).sort(); %>
  <% if (termIds.length === 0) { %>
    <p class="text-gray-500">No terms defined.</p>
  <% } else { %>
    <div class="space-y-4">
      <% for (var tid of termIds) { %>
        <% var term = terms[tid]; %>
        <div class="border rounded-lg p-4" id="term-<%= tid %>">
          <h2 class="text-lg font-semibold"><%= tid %></h2>
          <p class="text-gray-700 mt-1"><%= term.definition %></p>
          <% if (term.synonyms && term.synonyms.length > 0) { %>
            <div class="text-sm text-gray-500 mt-1">Synonyms: <%= term.synonyms.join(', ') %></div>
          <% } %>
          <% if (term.maps_to && term.maps_to.length > 0) { %>
            <div class="text-sm text-gray-500 mt-1">Maps to: <%= term.maps_to.join(', ') %></div>
          <% } %>
          <% if (term.owner) { %>
            <div class="text-sm text-gray-500 mt-1">Owner: <a href="<%= basePath %>/owners/<%= term.owner %>.html" class="text-blue-600 underline"><%= term.owner %></a></div>
          <% } %>
        </div>
      <% } %>
    </div>
  <% } %>
</main>
${FOOTER}
</body>
</html>`;

// ---------------------------------------------------------------------------
// Owner page template
// ---------------------------------------------------------------------------

export const ownerTemplate = `${HEAD}
<body class="bg-white text-gray-900 min-h-screen">
${NAV}
${TIER_BADGE}
<main class="max-w-5xl mx-auto p-6">
  <h1 class="text-3xl font-bold mb-2"><%= owner.display_name %></h1>
  <div class="text-sm text-gray-500 mb-4">
    <% if (owner.email) { %><span>Email: <%= owner.email %></span><% } %>
    <% if (owner.team) { %><span class="ml-4">Team: <%= owner.team %></span><% } %>
  </div>
  <% if (owner.description) { %>
    <p class="text-gray-600 mb-4"><%= owner.description %></p>
  <% } %>

  <% if (governedModels.length > 0) { %>
  <section>
    <h2 class="text-xl font-semibold mb-3">Governed Models</h2>
    <div class="space-y-2">
      <% for (var gm of governedModels) { %>
        <div class="flex items-center gap-3">
          <a href="<%= basePath %>/models/<%= gm.name %>.html" class="text-blue-600 hover:underline"><%= gm.name %></a>
          <% if (gm.tier) { %><%- tierBadge(gm.tier) %><% } %>
        </div>
      <% } %>
    </div>
  </section>
  <% } else { %>
    <p class="text-gray-500">No models governed by this owner.</p>
  <% } %>
</main>
${FOOTER}
</body>
</html>`;

// ---------------------------------------------------------------------------
// Search page template (client-side MiniSearch)
// ---------------------------------------------------------------------------

export const searchTemplate = `${HEAD}
<body class="bg-white text-gray-900 min-h-screen">
${NAV}
<main class="max-w-5xl mx-auto p-6">
  <h1 class="text-3xl font-bold mb-6">Search</h1>

  <input type="text" id="search-input"
         placeholder="Search models, datasets, terms..."
         class="w-full border rounded-lg px-4 py-2 mb-4 focus:outline-none focus:ring-2 focus:ring-blue-500" />

  <div id="search-results" class="space-y-2"></div>
</main>
${FOOTER}

<script src="https://cdn.jsdelivr.net/npm/minisearch@7.1.0/dist/umd/index.min.js"></script>
<script>
(function() {
  var indexData = <%- searchIndexJson %>;
  var miniSearch = MiniSearch.loadJSON(JSON.stringify(indexData.index), indexData.options);

  var input = document.getElementById('search-input');
  var resultsContainer = document.getElementById('search-results');
  var docs = indexData.documents;

  function clearResults() {
    while (resultsContainer.firstChild) {
      resultsContainer.removeChild(resultsContainer.firstChild);
    }
  }

  function createResultElement(doc) {
    var wrapper = document.createElement('div');
    wrapper.className = 'border rounded p-3';

    var link = document.createElement('a');
    link.href = doc.url;
    link.className = 'text-blue-600 font-medium hover:underline';
    link.textContent = doc.title;
    wrapper.appendChild(link);

    var badge = document.createElement('span');
    badge.className = 'ml-2 text-xs text-gray-400 uppercase';
    badge.textContent = doc.type;
    wrapper.appendChild(badge);

    if (doc.description) {
      var desc = document.createElement('p');
      desc.className = 'text-sm text-gray-600 mt-1';
      desc.textContent = doc.description;
      wrapper.appendChild(desc);
    }

    return wrapper;
  }

  input.addEventListener('input', function() {
    var query = input.value.trim();
    clearResults();
    if (!query) return;
    var hits = miniSearch.search(query, { prefix: true, fuzzy: 0.2 });
    if (hits.length === 0) {
      var noResults = document.createElement('p');
      noResults.className = 'text-gray-500';
      noResults.textContent = 'No results found.';
      resultsContainer.appendChild(noResults);
      return;
    }
    hits.slice(0, 20).forEach(function(hit) {
      var doc = docs[hit.id];
      if (doc) {
        resultsContainer.appendChild(createResultElement(doc));
      }
    });
  });
})();
</script>
</body>
</html>`;
