import { Command } from 'commander';
import chalk from 'chalk';
import path from 'node:path';
import fs from 'node:fs';
import { compile, loadConfig, emitManifest } from '@runcontext/core';
import type { Manifest, AIContext } from '@runcontext/core';
import { formatError, formatSuccess } from '../formatters/pretty.js';

export const blueprintCommand = new Command('blueprint')
  .description('Export AI Blueprints — portable, Gold-tier data product specs (OSI v1.0 YAML)')
  .argument('[model]', 'Model name to export (omit for all models)')
  .option('--context-dir <path>', 'Path to context directory')
  .option('--out <path>', 'Output directory for blueprint files', './blueprints')
  .option('--stdout', 'Print to stdout instead of writing files')
  .action(async (modelArg, opts) => {
    try {
      const config = loadConfig(process.cwd());
      const contextDir = opts.contextDir
        ? path.resolve(opts.contextDir)
        : path.resolve(config.context_dir);

      const { graph, diagnostics } = await compile({ contextDir, config, rootDir: process.cwd() });

      const errors = diagnostics.filter((d) => d.severity === 'error');
      if (errors.length > 0) {
        console.error(chalk.red(`Build failed with ${errors.length} error(s). Run "context build" to see details.`));
        process.exit(1);
      }

      const manifest = emitManifest(graph, config);
      const modelNames = modelArg
        ? [modelArg]
        : Object.keys(manifest.models);

      if (modelNames.length === 0) {
        console.error(chalk.yellow('No models found. Run "context introspect" first.'));
        process.exit(1);
      }

      // Validate requested model exists
      if (modelArg && !manifest.models[modelArg]) {
        const available = Object.keys(manifest.models).join(', ');
        console.error(formatError(`Model "${modelArg}" not found. Available: ${available}`));
        process.exit(1);
      }

      if (!opts.stdout) {
        const outDir = path.resolve(opts.out);
        fs.mkdirSync(outDir, { recursive: true });
      }

      for (const name of modelNames) {
        const yaml = emitBlueprint(name, manifest);

        if (opts.stdout) {
          if (modelNames.length > 1) {
            console.log(chalk.gray(`# ── ${name} ${'─'.repeat(60 - name.length)}`));
          }
          console.log(yaml);
        } else {
          const outDir = path.resolve(opts.out);
          const filePath = path.join(outDir, `${name}.data-product.osi.yaml`);
          fs.writeFileSync(filePath, yaml, 'utf-8');
          console.log(formatSuccess(`${filePath}`));
        }
      }

      if (!opts.stdout) {
        const outDir = path.resolve(opts.out);
        console.log(
          chalk.blue(`\n${modelNames.length} AI Blueprint(s) written to ${outDir}/`),
        );
        console.log(chalk.gray('These portable YAML files contain the full semantic spec for each data product.'));
        console.log(chalk.gray('Share them, serve them via MCP, or import them into any OSI-compliant tool.'));
      }
    } catch (err) {
      console.error(formatError((err as Error).message));
      process.exit(1);
    }
  });

/**
 * Emit a single model as a full OSI-compliant data product YAML.
 */
function emitBlueprint(name: string, manifest: Manifest): string {
  const model = manifest.models[name];
  const governance = manifest.governance[name];
  const rules = manifest.rules[name];
  const tier = manifest.tiers[name];

  const lines: string[] = [];

  // Header
  lines.push(`# ${name}.data-product.osi.yaml`);
  lines.push(`# AI Blueprint — Open Semantic Interchange (OSI) v1.0`);
  lines.push(`# The complete semantic spec for this data product, ready for any AI agent`);
  lines.push(`# Generated by ContextKit (context blueprint)`);
  lines.push(``);
  lines.push(`osi_version: "1.0"`);
  lines.push(``);
  lines.push(`semantic_model:`);
  lines.push(`  name: ${name}`);

  if (model?.description) {
    lines.push(`  description: >`);
    wrapText(lines, model.description, 4);
  }

  // Governance header
  if (governance) {
    if (governance.owner) lines.push(`  owner: ${governance.owner}`);
    if (governance.trust) lines.push(`  trust_status: ${governance.trust}`);
  }
  if (tier) {
    lines.push(`  tier: ${tier.tier ?? 'bronze'}`);
  }
  if (governance?.tags && governance.tags.length > 0) {
    lines.push(`  tags:`);
    for (const tag of governance.tags) {
      lines.push(`    - ${tag}`);
    }
  }

  // Glossary (terms that reference this model)
  const relatedTerms = Object.entries(manifest.terms).filter(([, term]) => {
    const maps = term.maps_to ?? [];
    return maps.some((m) => m.startsWith(`${name}.`));
  });
  if (relatedTerms.length > 0) {
    lines.push(``);
    lines.push(`  # ── Glossary ────────────────────────────────────────────────`);
    lines.push(`  glossary:`);
    for (const [, term] of relatedTerms) {
      lines.push(`    - term: ${term.id}`);
      if (term.definition) {
        lines.push(`      definition: >`);
        wrapText(lines, term.definition, 8);
      }
      if (term.synonyms && term.synonyms.length > 0) {
        lines.push(`      synonyms:`);
        for (const s of term.synonyms) {
          lines.push(`        - ${s}`);
        }
      }
      if (term.maps_to && term.maps_to.length > 0) {
        lines.push(`      related_fields:`);
        for (const m of term.maps_to) {
          lines.push(`        - ${m}`);
        }
      }
    }
  }

  // Datasets
  if (model?.datasets && model.datasets.length > 0) {
    lines.push(``);
    lines.push(`  # ── Datasets ────────────────────────────────────────────────`);
    lines.push(`  datasets:`);
    for (const ds of model.datasets) {
      lines.push(`    - name: ${ds.name}`);
      if (ds.description) {
        lines.push(`      description: ${yamlStr(ds.description)}`);
      }
      if (ds.source) lines.push(`      source: ${ds.source}`);
      if (ds.primary_key && ds.primary_key.length > 0) {
        lines.push(`      primary_key: [${ds.primary_key.join(', ')}]`);
      }

      // Dataset-level governance
      const dsGov = governance?.datasets?.[ds.name];
      if (dsGov) {
        if (dsGov.grain) lines.push(`      grain: ${dsGov.grain}`);
        if (dsGov.table_type) lines.push(`      table_type: ${dsGov.table_type}`);
      }

      if (ds.ai_context) {
        emitAiContext(lines, ds.ai_context, 6);
      }

      // Fields
      if (ds.fields && ds.fields.length > 0) {
        lines.push(`      fields:`);
        for (const f of ds.fields) {
          lines.push(`        - name: ${f.name}`);
          if (f.expression) {
            const expr = typeof f.expression === 'string' ? f.expression : JSON.stringify(f.expression);
            lines.push(`          expression: ${expr}`);
          }
          if (f.description) {
            lines.push(`          description: ${yamlStr(f.description)}`);
          }
          if (f.dimension) lines.push(`          dimension: true`);
          if (f.label) lines.push(`          label: true`);

          // Field-level governance
          const fGov = governance?.fields?.[`${ds.name}.${f.name}`] ?? governance?.fields?.[f.name];
          if (fGov) {
            if (fGov.semantic_role) lines.push(`          semantic_role: ${fGov.semantic_role}`);
            if (fGov.default_aggregation) lines.push(`          aggregation: ${fGov.default_aggregation}`);
            if (fGov.sample_values && fGov.sample_values.length > 0) {
              lines.push(`          sample_values:`);
              for (const sv of fGov.sample_values) {
                lines.push(`            - ${sv}`);
              }
            }
            if (fGov.default_filter) lines.push(`          default_filter: ${yamlStr(fGov.default_filter)}`);
          }

          if (f.ai_context) {
            emitAiContext(lines, f.ai_context, 10);
          }
        }
      }
    }
  }

  // Relationships
  if (model?.relationships && model.relationships.length > 0) {
    lines.push(``);
    lines.push(`  # ── Relationships ───────────────────────────────────────────`);
    lines.push(`  relationships:`);
    for (const rel of model.relationships) {
      lines.push(`    - name: ${rel.name}`);
      lines.push(`      from:`);
      lines.push(`        dataset: ${rel.from}`);
      lines.push(`        columns: [${rel.from_columns.join(', ')}]`);
      lines.push(`      to:`);
      lines.push(`        dataset: ${rel.to}`);
      lines.push(`        columns: [${rel.to_columns.join(', ')}]`);
      if (rel.cardinality) lines.push(`      cardinality: ${rel.cardinality}`);
    }
  }

  // Metrics
  if (model?.metrics && model.metrics.length > 0) {
    lines.push(``);
    lines.push(`  # ── Metrics ─────────────────────────────────────────────────`);
    lines.push(`  metrics:`);
    for (const met of model.metrics) {
      lines.push(`    - name: ${met.name}`);
      if (met.expression) {
        const expr = typeof met.expression === 'string' ? met.expression : JSON.stringify(met.expression);
        lines.push(`      expression: ${expr}`);
      }
      if (met.description) {
        lines.push(`      description: ${yamlStr(met.description)}`);
      }
      if (met.ai_context) {
        emitAiContext(lines, met.ai_context, 6);
      }
    }
  }

  // Business rules
  if (rules?.business_rules && rules.business_rules.length > 0) {
    lines.push(``);
    lines.push(`  # ── Business Rules ──────────────────────────────────────────`);
    lines.push(`  business_rules:`);
    for (const br of rules.business_rules) {
      lines.push(`    - name: ${br.name}`);
      if (br.definition) lines.push(`      definition: ${yamlStr(br.definition)}`);
      if (br.enforcement && br.enforcement.length > 0) {
        lines.push(`      enforcement:`);
        for (const e of br.enforcement) {
          lines.push(`        - ${yamlStr(e)}`);
        }
      }
      if (br.avoid && br.avoid.length > 0) {
        lines.push(`      avoid:`);
        for (const a of br.avoid) {
          lines.push(`        - ${yamlStr(a)}`);
        }
      }
      if (br.applied_always) lines.push(`      applied_always: true`);
    }
  }

  // Guardrail filters
  if (rules?.guardrail_filters && rules.guardrail_filters.length > 0) {
    lines.push(``);
    lines.push(`  # ── Guardrails ──────────────────────────────────────────────`);
    lines.push(`  guardrail_filters:`);
    for (const gf of rules.guardrail_filters) {
      lines.push(`    - name: ${gf.name}`);
      if (gf.reason) lines.push(`      reason: ${yamlStr(gf.reason)}`);
      if (gf.filter) lines.push(`      filter: ${yamlStr(gf.filter)}`);
      if (gf.tables && gf.tables.length > 0) {
        lines.push(`      tables: [${gf.tables.join(', ')}]`);
      }
    }
  }

  // Golden queries
  if (rules?.golden_queries && rules.golden_queries.length > 0) {
    lines.push(``);
    lines.push(`  # ── Golden Queries ──────────────────────────────────────────`);
    lines.push(`  golden_queries:`);
    for (const gq of rules.golden_queries) {
      lines.push(`    - question: ${yamlStr(gq.question)}`);
      if (gq.intent) lines.push(`      intent: ${yamlStr(gq.intent)}`);
      if (gq.sql) {
        lines.push(`      sql: |`);
        for (const sqlLine of gq.sql.split('\n')) {
          lines.push(`        ${sqlLine}`);
        }
      }
      if (gq.dialect) lines.push(`      dialect: ${gq.dialect}`);
      if (gq.caveats) lines.push(`      caveats: ${yamlStr(gq.caveats)}`);
    }
  }

  lines.push(``);
  return lines.join('\n');
}

/** Emit ai_context as YAML (string or AIContext object format). */
function emitAiContext(lines: string[], ctx: string | AIContext, indent: number): void {
  const pad = ' '.repeat(indent);
  if (typeof ctx === 'string') {
    lines.push(`${pad}ai_context: ${yamlStr(ctx)}`);
  } else {
    lines.push(`${pad}ai_context:`);
    if (ctx.instructions) {
      lines.push(`${pad}  instructions: >`);
      wrapText(lines, ctx.instructions, indent + 4);
    }
    if (ctx.synonyms && ctx.synonyms.length > 0) {
      lines.push(`${pad}  synonyms:`);
      for (const s of ctx.synonyms) {
        lines.push(`${pad}    - ${s}`);
      }
    }
    if (ctx.examples && ctx.examples.length > 0) {
      lines.push(`${pad}  examples:`);
      for (const e of ctx.examples) {
        lines.push(`${pad}    - ${yamlStr(e)}`);
      }
    }
  }
}

/** Quote a string for safe YAML output. */
function yamlStr(s: string): string {
  if (s.includes('\n') || s.includes(': ') || s.includes('#') || s.includes('"') || s.includes("'")) {
    return JSON.stringify(s);
  }
  return s;
}

/** Wrap long text into indented lines. */
function wrapText(lines: string[], text: string, indent: number): void {
  const pad = ' '.repeat(indent);
  const words = text.replace(/\n/g, ' ').split(/\s+/);
  let line = '';
  for (const word of words) {
    if (line.length + word.length + 1 > 76) {
      lines.push(`${pad}${line.trim()}`);
      line = '';
    }
    line += word + ' ';
  }
  if (line.trim()) {
    lines.push(`${pad}${line.trim()}`);
  }
}
